alias gs='git status'
alias gp='git push'
alias gc='git commit -m '
alias ga='git add '
alias g='./gradlew'
alias jdk11='export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/; export PATH=$JAVA_HOME/bin:$PATH'
alias update_fork='git fetch upstream && git checkout master && git merge upstream/master'
